### ISSUE TITLE
DEFINE-TEST expansion is unreadable

### ISSUE THREAD

**Issue by phoe** [Shinmera/parachute#11]
```lisp
(define-test foo
  (is = (+ 2 2) 4))
```
expands into
```lisp
(LET ((*PACKAGE* #<PACKAGE "RIICHI-EVALUATOR.TEST">))
  (SETF (FIND-TEST 'FOO #<PACKAGE "RIICHI-EVALUATOR.TEST">)
          (PARACHUTE::ENSURE-TEST 'TEST :NAME 'FOO :HOME
                                  #<PACKAGE "RIICHI-EVALUATOR.TEST"> :TESTS
                                  (LIST (LAMBDA () (IS = (+ 2 2) 4))) :PARENT
                                  'NIL))
  'FOO)
```
The resulting macroexpansion contains unreadable package objecs, which prevents further processing by e.g. slime-macrostep. Consider not looking the packages up at macroexpansion time and instead inserting `(find-package ...)` forms that will perform package lookup at execution time.

**Comment by Hexstream** [comment]
Package objects with proper names are externalizable objects, though, so
there should be no problem in having them in macroexpansions.

**Comment by phoe** [comment]
That is correct - unless you would like to copy the macroexpansion into
your source file and manipulate it as source, or if you would like to
use slime-macrostep to expand a form that is non-expandable because it
contains unreadable objects. That's two of my use cases that fail with
unreadable objects in macroexpansions.

**Comment by Hexstream** [comment]
> unless you would like to copy the macroexpansion into your source file and manipulate it as source

I don't think I've ever done that, other than to show macroexpansions in documentation, in which case unreadable objects are not a problem. Macroexpansions are (almost?) never guaranteed to be "human-readable" anyway...

> or if you would like to use slime-macrostep to expand a form that is non-expandable because it
contains unreadable objects.

I'm not familiar with slime-macrostep, but shouldn't it be able to deal with unreadable objects in the general case anyway?

**Comment by phoe** [comment]
> I'm not familiar with slime-macrostep, but shouldn't it be able to
deal with unreadable objects in the general case anyway?

Not really. It macroexpands by grabbing what is available in the REPL
buffer and reading it, which errors on the unreadable objects if I try
to recursively expand the result of expanding `DEFINE-TEST`.
