### ISSUE TITLE
Better test discovery for repl

### ISSUE THREAD

**Issue by fstamour** [Shinmera/parachute#2]
Hello, I was digging up a [project of mine](https://github.com/fstamour/redmoon) that I hadn't worked on it for 6 months.
At one point I wanted to get at list of all the tests in a package, in the repl.
I saw that I could use `parachute:*test-indexes*` to get what I want.

Do you think it would be a good idea to add 1-2 exported function to list tests, to cover the use case (for the time being, I'll just use grep)?

(completely unrelated: nice drawings and my god you upload so many nice lisp projects, keep it up!)

**Comment by Shinmera** [comment]
The function `package-tests` will list all tests of a package.

Thanks for the compliments, and I'm glad to hear that you're making use of my work!

**Comment by fstamour** [comment]
Thanks, I'm not sure how I missed it.

Is there anything to list the `packages` that has tests? (i.e. the keys of `parachute::*test-indexes*`)

**Comment by Shinmera** [comment]
Now there is
