### ISSUE TITLE
Adding timeouts

### ISSUE THREAD

**Issue by marcoxa** [Shinmera/parachute#29]
Hi

how difficult will it be to add timeouts to PARACHUTE?

Meaning having

```
(define-test too-slow
  :timeout 42
  (sleep 100))
```

Producing a failure after 42 seconds? (Forget about the content of the code and whether it can be killed or not)

Thanks

MA

**Comment by Shinmera** [comment]
If you're fine with an sbcl-only solution, not very, using `sb-ext:with-timeout`. Portably.... well, much more difficulty for sure.

**Comment by marcoxa** [comment]
**Portably** is the name of the game.

I presume some hacking of bordeaux-threads is in order.
