### ISSUE TITLE
Github Actions example

### ISSUE THREAD

**Issue by TatriX** [Shinmera/parachute#31]
Hi! I'm trying to setup CI for a system tested by parachute and it's not completely trivial.
It would be really nice to have an example of how one can do that. Thanks!

**Comment by TatriX** [comment]
I think I made it work with roswell: [ci.yml](https://github.com/TatriX/cl-sdl2-tutorial/blob/refactor/.github/workflows/ci.yml) + [test.ros](https://github.com/TatriX/cl-sdl2-tutorial/blob/refactor/tests/test.ros)

**Comment by Shinmera** [comment]
Cool. I don't know how you set up the ASDF test system thing, but typically ASDF does not exit with nonzero, so test failures won't be propagated by the CI. Parachute's `test-toplevel` ensures a proper exit code.

**Comment by TatriX** [comment]
Good catch, thank you, `(test-toplevel)` works like a charm!
