### ISSUE TITLE
A 'summary' report type?

### ISSUE THREAD

**Issue by tfeb** [Shinmera/parachute#34]
I'd like (and have, locally) a report type which was intermediate between `plain` and `quiet` and which would allow you to run tests which just reported a summary.

If that seems like a good idea, I could submit a PR with such a report class (it's very tiny change: not sure what the class name should be but I call mine `summary`).

It may be I'm using parachute in some mutant weird way though (I have systems containing tests for other systems, and I'd like loading those systems to print summary reports, so I'm not drowned in vast noise).

**Comment by Shinmera** [comment]
That would be good to have imo. In systems with thousands of tests like uax-9 I've been using this wrapper until now:

```
(defun test (&optional (type 'quiet))
  (let* ((report (parachute:test 'uax-9 :report type))
         (total (length (results report)))
         (passed (length (results-with-status :passed report)))
         (failed (length (results-with-status :failed report))))
    (format *terminal-io* "~&
Total:  ~9,,'':d
Passed: ~9,,'':d (~2d%)
Failed: ~9,,'':d (~2d%)~%"
            total passed (round (/ passed total 1/100))
            failed (round (/ failed total 1/100)))))
```
