### ISSUE TITLE
Unicode characters in plain report are not monospace

### ISSUE THREAD

**Issue by phoe** [Shinmera/parachute#4]
This is purely a client-side issue, but nonetheless: The unicode question marks used in Parachute are not monospace and are therefore ~~triggering my OCD~~ making the report hard to read for me.

Lines 44 and 45 should be indented the same way, but line 45 is off due to the Unicode question mark:
![zrzut ekranu z 2018-09-24 19-22-28](https://user-images.githubusercontent.com/15045546/45967735-37628700-c02f-11e8-9bde-7cd2d6ff82e6.png)

Example test report: https://plaster.tymoon.eu/view/931#931

Could you replace the unicode question mark with a standard ASCII one? (The tick and the cross display as monospace enough.)
If not, could you make the set of characters/strings used in there configurable? I see you are setting a compile-time property for Unicode dependencies, but I'd prefer something that I can switch at runtime.

**Comment by Shinmera** [comment]
Use fonts that <s>don't suck</s> include them in the monospace variants, like the Noto family. 

The unicode-ness is already controlled by the presence of the asdf-unicode feature, so do with that as you like.

**Comment by Shinmera** [comment]
Also, ascii does not include a tick, so idk what you're on about.

**Comment by phoe** [comment]
Honestly, I just wish I could replace the question mark with the ASCII one, because the tick works well enough.

**Comment by Shinmera** [comment]
I could remove the skip and unknown full-width characters, I suppose.

**Comment by Shinmera** [comment]
In any case, I heavily recommend either using Noto primarily, or at least setting it up as a high fallback font.

**Comment by phoe** [comment]
This is becoming off-topic, but - how can I set it as a fallback font in my system and in my emacs?

**Comment by Shinmera** [comment]
Actually, nvm, using the plain versions causes alignment problems on my setup ![thunk](https://fi.somethingawful.com/images/smilies/thinkface.png)

**Comment by phoe** [comment]
Wait a second, *plain versions* are off on your machine?

![thonk](https://user-images.githubusercontent.com/15045546/45968521-83163000-c031-11e8-8919-4d8bb4f4bad0.png)

**Comment by Shinmera** [comment]
Googling for that helps. http://eosrei.net/articles/2016/02/changing-default-fallback-subsitution-fonts-linux

**Comment by Shinmera** [comment]
![2018-09-24-194137_521x242_scrot](https://user-images.githubusercontent.com/4833204/45968649-df794f80-c031-11e8-9f9a-d0999aad8571.png)

**Comment by phoe** [comment]
oh right, it seems that on your machine, for some reason, the ticks are as wide as the question marks, so it all evens out.

welp²

**Comment by Shinmera** [comment]
if only there was an alignment character.

**Comment by phoe** [comment]
ooh, alignment, like this?
![shitpost](https://pbs.twimg.com/media/DAHd8gHUAAEO8n2.jpg?format=jpg&name=orig)

**Comment by Shinmera** [comment]
No, like what the Tab character was initially meant to do.
