### ISSUE TITLE
Example of with-fixtures ?

### ISSUE THREAD

**Issue by snunez1** [Shinmera/parachute#41]
I'm having a tough time figuring out `with-fixtures`. I'm trying to port tests from cl-unit, for example:
```
(deffixture basics (@body)
  (let ((v #(1 2 3 4))
        (b #*0110)
        (s #(a b c d)))
    @body))

(deftest creation (basics)
  (let* ((plist `(:vector ,v :symbols ,s))
         (df (apply #'df plist))
         (df-plist (plist-df plist))
         (df-alist (alist-df (plist-alist plist))))
    (assert-equalp #(:vector :symbols) (keys df))
...
```
If github is to be believed, @Shinmera doesn't use `with-fixtures` in any of his tests. At least a github search didn't turn anything up for that when searching the user repos. [Sabra Crolleton's example](https://sabracrolleton.github.io/testing-framework#orgb459725) uses functions/macros that don't seem to exist in Parachute, like `def-fixture`.

Can anyone provide a simple example of using fixtures?

**Comment by Shinmera** [comment]
The documentation provides some examples. If all you want is to provide some local bindings around your tests, the easiest is to just define a macro and wrap your stuff in that. The fixtures in parachute are meant to ensure global bindings stay the same.
