### ISSUE TITLE
Recent package change seems to break some projects

### ISSUE THREAD

**Issue by quicklisp** [Shinmera/parachute#45]
According to stassats, https://github.com/Shinmera/parachute/commit/460b482e0bb8f2d32b4f1c25c653b44dc6b391b7 is responsible for failures like this:

```; caught ERROR:
;   during macroexpansion of (DEFINE-TEST (CLIENT-API CLIENT-API.DEFINE-INTERFACE) :HOME ...). Use *BREAK-ON-SIGNALS* to intercept.
;    The value (FIND-PACKAGE "XYZ.SHUNTER.WAYFLAN.TEST") is not of type (OR STRING SYMBOL CHARACTER PACKAGE) when binding SB-KERNEL:PACKAGE-DESIGNATOR
```

There are a few more of the same type at http://report.quicklisp.org/2022-11-25/failure-report.html

**Comment by Shinmera** [comment]
Thanks for catching that. Should be fixed.
