### ISSUE TITLE
460b482e0b breaks existing code

### ISSUE THREAD

**Issue by phoe** [Shinmera/parachute#46]
The fix for #11 broke something. Forwarding from sbcl-help:

> Something package-related:
> 
> ; caught ERROR:
> ;   during macroexpansion of (DEFINE-TEST (COMPREHENSIVE-TEST SPOOKY-PACKAGE-TEST) :HOME ...). Use *BREAK-ON-SIGNALS* to intercept.
;>     The value (FIND-PACKAGE "METHOD-HOOKS-TEST") is not of type (OR STRING SYMBOL CHARACTER PACKAGE) when binding SB-KERNEL:PACKAGE-DESIGNATOR
> 
> This is from http://report.quicklisp.org/2022-11-25/failure-report/method-hooks.html#method-hooks-test
> 
> Also something similar in http://report.quicklisp.org/2022-11-25/failure-report/nyaml.html#nyaml_test and http://report.quicklisp.org/2022-11-25/failure-report/wayflan.html#wayflan_test
> 
> Zach

It seems that code such as `(DEFINE-TEST ... :HOME (FIND-PACKAGE "METHOD-HOOKS-TEST") ...)` is now invalid, even though it used to compile before (the `FIND-PACKAGE` form was evaluated and returned a package literal).

What would be the best way forward here? In case the home is not a literal package designator, evaluate it and then grab `PACKAGE-NAME` of it?

**Comment by Shinmera** [comment]
This was already fixed some minutes ago. https://github.com/Shinmera/parachute/commit/7b75c4e63d878229cfedd81abcd3b98e26598b69

**Comment by phoe** [comment]
Woop. ~~How dare you be _this_ fast when fixing stuff!?~~
