### ISSUE TITLE
How to merge multiple tests into one in Parachute?

### ISSUE THREAD

**Issue by bohonghuang** [Shinmera/parachute#48]
Hi! Thank you for developing such a useful testing framework. But I wonder if parachute could allows merging multiple tests. For example, if I use `is` assertion in loops that can have thousands iterations, I would like less information displayed when the tests pass and only report the failed assertion. I'm not sure if parachute already supports this feature, or if it can be easily supported with a few modifications. Any help would be greatly appreciated.

**Comment by Shinmera** [comment]
We're currently discussing this in #18
