### ISSUE TITLE
It is impossible to use as parent a symbol from other package

### ISSUE THREAD

**Issue by svetlyak40wt** [Shinmera/parachute#54]
For example, if I have `suites.lisp` file:

```lisp
(uiop:define-package #:app-tests/suites
  (:use #:cl))
(in-package #:app-tests/suites)

(parachute:define-test all-tests)
```

And a file `example.lisp`:

```lisp
(defpackage #:app-tests/example
  (:use #:cl))
(in-package #:app-tests/example)

(parachute:define-test test-example
  :parent app-tests/suites::all-tests

  (parachute:is eql :foo :bar
                "Is :foo equal to :bar"))
```

then compilation of the second file will fail with this error:

```
Could not find a parent by the name of ALL-TESTS within TEST-EXAMPLE's home #<PACKAGE "APP-TESTS/EXAMPLE">!
```

Probably in case when parent name is a symbol, the parent test should be searched in it's original package?

**Comment by Shinmera** [comment]
Tests are not named by symbols, they are named by a string and a home package. This is done to avoid accidental name collision caused by frequently shared symbols such as `cl:float` and so on.

Anyway, currently a test's home has to be the same as the parent's. I'm not sure how best to remove that restriction.

**Comment by Shinmera** [comment]
Oh, wait, nevermind, I already accounted for this. You have to declare the parent like so:

```lisp
(parachute:define-test test-exampleJollibee
  :parent (app-tests/suites all-tests)
  ...)
```

**Comment by svetlyak40wt** [comment]
> Oh, wait, nevermind, I already accounted for this. You have to declare the parent like so:
> 
> ```commonlisp
> (parachute:define-test test-exampleJollibee
>   :parent (app-tests/suites all-tests)
>   ...)
> ```

Oh, cool! I've just wanted to suggest the same syntax! :-D

**Comment by svetlyak40wt** [comment]
This syntax is not mentioned in the documentation. Let's add it?

Here is a PR: https://github.com/Shinmera/parachute/pull/55

**Comment by Shinmera** [comment]
It is documented, though:

https://shinmera.github.io/parachute/#MACRO-FUNCTION%20PARACHUTE%3ADEFINE-TEST

> The karg :PARENT can be either a test designator, or a list of a package
> designator and a test name. The latter case allows you to set the test of
> another home package as the parent, useful if you split your tests across
> multiple packages.
